# Generated by Django 2.2.6 on 2019-11-20 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='equipa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appEball.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
