# Generated by Django 2.2.6 on 2019-11-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileImg',
            field=models.ImageField(upload_to='images'),
        ),
    ]
