# Generated by Django 2.2.7 on 2019-11-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'db_table': 'Tournament',
            },
        ),
    ]
