# Generated by Django 2.2.6 on 2019-11-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0002_auto_20191117_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
