# Generated by Django 2.2.6 on 2019-11-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0002_auto_20191118_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isSeen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(),
        ),
    ]
