# Generated by Django 2.2.7 on 2019-11-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0002_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='data',
            field=models.DateTimeField(verbose_name='Tournament Date'),
        ),
    ]
