# Generated by Django 2.2.7 on 2019-11-18 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0003_auto_20191118_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='data',
        ),
        migrations.AddField(
            model_name='tournament',
            name='datafim',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Tournament End Date'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='datainicio',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Tournament Start Date'),
        ),
    ]
