# Generated by Django 2.2.7 on 2019-11-18 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0004_auto_20191118_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='datafim',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='datainicio',
        ),
        migrations.AddField(
            model_name='tournament',
            name='beginDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Tournament Start Date'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='endDate',
            field=models.DateField(default=datetime.date.today, verbose_name='Tournament End Date'),
        ),
    ]
