# Generated by Django 2.2.7 on 2019-11-18 20:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0006_tournament_maxteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='gameDays',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sun', 'Sun'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat')], default=None, max_length=27),
        ),
    ]
