# Generated by Django 2.2.7 on 2019-11-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0007_tournament_gamedays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tactic', models.CharField(default=None, max_length=100)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'Team',
            },
        ),
    ]
