# Generated by Django 2.2.7 on 2019-11-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEball', '0008_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tactic',
            field=models.CharField(choices=[('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('4-2-3-1', '4-2-3-1'), ('4-1-2-1-2', '4-1-2-1-2')], default=None, max_length=100),
        ),
    ]
